#!/usr/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body)
{
  // simulate a document object model
  let { document} = (new JSDOM(body)).window;

  // grab all the paragraphs and references
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");

  // remove any references
  references.forEach(function(reference)
  {
    reference.remove();
  });

  // print out all the paragraphs
  paragraphs.forEach(function(paragraph)
  {
    console.log(paragraph.textContent);
  });
});

